### ISSUE TITLE
Retina image is not loading in image popup

### ISSUE THREAD

**Issue by SiDDeR** [themejunkie/silvia#10]
Hello, retina image is not loading on image popup in mobile devices.
As is seems @2x file is missing and not creating automatically.
![image](https://cloud.githubusercontent.com/assets/16826111/12495147/d67123c4-c096-11e5-84a3-1f30b9828bf3.png)

**Comment by gasatrya** [comment]
I'm sorry for late reply, we will check this issue soon. Thank you for reporting!

**Comment by gasatrya** [comment]
I temporary removed this feature until I found the best solution, please update to 1.0.7
