### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by Colbize** [themejunkie/silvia#11]
The search bar is not working at all for web or mobile.  Both return "Nothing Found" regardless of search.  Appears to be an issue specifically with this theme as search works on site with other themes.

**Comment by gasatrya** [comment]
Are you using a plugin for something like extend the search function? The search on our demo working fine http://demo.theme-junkie.com/silvia/?s=woman

**Comment by gasatrya** [comment]
Everything works fine, please add more detail information. But, please open new issue if you think it's a bug
