### ISSUE TITLE
Scrolling to bottom on homepage

### ISSUE THREAD

**Issue by akashisama** [themejunkie/silvia#14]
When scrolling to the bottom of the final page of home, the final row of posts is removed unexpectedly.
To replicate, go to the demo site http://demo.theme-junkie.com/?theme=silvia

Scroll to bottom, click "older posts", scroll to the bottom again, click "older posts", notice that there is one last post whose icon can be partly seen, scroll to the bottom, the last post disappears unexpectedly.

**Comment by gasatrya** [comment]
Hm.. I have no idea, but it is possible bug from Jetpack infinite scroll
